"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _ios_entry from './ios-entry.bones.json'

configureBoneyard({"color":"var(--muted)","darkColor":"var(--muted)","animate":"shimmer","shimmerColor":"var(--panel-border)","darkShimmerColor":"var(--panel-border)","speed":"1.6s","shimmerAngle":110})

registerBones({
  "ios-entry": _ios_entry,
})
